(deftheme spacemacs-dark-disable-background
  "Created 2017-06-25.")

(custom-theme-set-variables
 'spacemacs-dark-disable-background
 '(ansi-color-names-vector ["#080808" "#d70000" "#67b11d" "#875f00" "#268bd2" "#af00df" "#00ffff" "#b2b2b2"]))

(custom-theme-set-faces
 'spacemacs-dark-disable-background
 '(cursor ((((class color) (min-colors 89)) (:background "#d0d0d0"))))
 '(custom-button ((((class color) (min-colors 89)) :background "#1c1c1c" :foreground "#b2b2b2" :box (:line-width 2 :style released-button))))
 '(error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(eval-sexp-fu-flash ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "#262626"))))
 '(eval-sexp-fu-flash-error ((((class color) (min-colors 89)) (:background "#e0211d" :foreground "#262626"))))
 '(font-lock-builtin-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(font-lock-comment-face ((t (:foreground "#008787"))))
 '(font-lock-constant-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-doc-face ((((class color) (min-colors 89)) (:foreground "#008787"))))
 '(font-lock-function-name-face ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(font-lock-keyword-face ((((class color) (min-colors 89)) (:inherit bold :foreground "#268bd2"))))
 '(font-lock-negation-char-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-preprocessor-face ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(font-lock-string-face ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(font-lock-type-face ((((class color) (min-colors 89)) (:foreground "#df005f" :inherit bold))))
 '(font-lock-variable-name-face ((((class color) (min-colors 89)) (:foreground "#8787d7"))))
 '(font-lock-warning-face ((((class color) (min-colors 89)) (:foreground "#dc752f" :background "#262626"))))
 '(fringe ((((class color) (min-colors 89)) (:background "#262626" :foreground "#b2b2b2"))))
 '(header-line ((((class color) (min-colors 89)) :background "#080808")))
 '(highlight ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#444444"))))
 '(hl-line ((((class color) (min-colors 89)) (:background "#1c1c1c"))))
 '(isearch ((((class color) (min-colors 89)) (:foreground "#262626" :background "#86dc2f"))))
 '(lazy-highlight ((((class color) (min-colors 89)) (:background "#262626" :weight normal))))
 '(link ((((class color) (min-colors 89)) (:foreground "#008787" :underline t))))
 '(link-visited ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline t))))
 '(match ((((class color) (min-colors 89)) (:background "#444444" :foreground "#86dc2f"))))
 '(minibuffer-prompt ((((class color) (min-colors 89)) (:inherit bold :foreground "#268bd2"))))
 '(page-break-lines ((((class color) (min-colors 89)) (:foreground "#444444"))))
 '(region ((((class color) (min-colors 89)) (:background "#444444"))))
 '(secondary-selection ((((class color) (min-colors 89)) (:background "#121212"))))
 '(shadow ((((class color) (min-colors 89)) (:foreground "#585858"))))
 '(success ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(tooltip ((((class color) (min-colors 89)) (:background "#333333" :foreground "#b2b2b2" :bold nil :italic nil :underline nil))))
 '(vertical-border ((((class color) (min-colors 89)) (:foreground "#111111"))))
 '(warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(ahs-face ((((class color) (min-colors 89)) (:background "#444444"))))
 '(ahs-plugin-whole-buffer-face ((((class color) (min-colors 89)) (:background "#86dc2f" :foreground "#262626"))))
 '(anzu-mode-line ((((class color) (min-colors 89)) (:foreground "#875f00" :inherit bold))))
 '(company-echo-common ((((class color) (min-colors 89)) (:background "#b2b2b2" :foreground "#262626"))))
 '(company-preview ((((class color) (min-colors 89)) (:background "#444444" :foreground "#888888"))))
 '(company-preview-common ((((class color) (min-colors 89)) (:background "#444444" :foreground "#b2b2b2"))))
 '(company-preview-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-scrollbar-bg ((((class color) (min-colors 89)) (:background "#1c1c1c"))))
 '(company-scrollbar-fg ((((class color) (min-colors 89)) (:background "#444444"))))
 '(company-template-field ((((class color) (min-colors 89)) (:inherit region))))
 '(company-tooltip ((((class color) (min-colors 89)) (:background "#444444" :foreground "#888888"))))
 '(company-tooltip-annotation ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(company-tooltip-common ((((class color) (min-colors 89)) (:background "#444444" :foreground "#b2b2b2"))))
 '(company-tooltip-common-selection ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(company-tooltip-mouse ((((class color) (min-colors 89)) (:inherit highlight))))
 '(company-tooltip-search ((((class color) (min-colors 89)) (:inherit match))))
 '(company-tooltip-selection ((((class color) (min-colors 89)) (:background "#333333" :foreground "#b2b2b2"))))
 '(diff-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-changed ((((class color) (min-colors 89)) :background nil :foreground "#268bd2")))
 '(diff-header ((((class color) (min-colors 89)) :background "#333333" :foreground "#d75fd7")))
 '(diff-file-header ((((class color) (min-colors 89)) :background "#333333" :foreground "#b2b2b2")))
 '(diff-indicator-added ((((class color) (min-colors 89)) :background nil :foreground "#67b11d")))
 '(diff-indicator-changed ((((class color) (min-colors 89)) :background nil :foreground "#268bd2")))
 '(diff-indicator-removed ((((class color) (min-colors 89)) :background nil :foreground "#d70000")))
 '(diff-refine-added ((((class color) (min-colors 89)) :background "#67b11d" :foreground "#080808")))
 '(diff-refine-changed ((((class color) (min-colors 89)) :background "#268bd2" :foreground "#080808")))
 '(diff-refine-removed ((((class color) (min-colors 89)) :background "#d70000" :foreground "#080808")))
 '(diff-removed ((((class color) (min-colors 89)) :background nil :foreground "#d70000")))
 '(diff-hl-change ((((class color) (min-colors 89)) :background "#262626" :foreground "#268bd2")))
 '(diff-hl-delete ((((class color) (min-colors 89)) :background "#262626" :foreground "#d70000")))
 '(diff-hl-insert ((((class color) (min-colors 89)) :background "#262626" :foreground "#67b11d")))
 '(dired-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#262626" :inherit bold))))
 '(dired-flagged ((((class color) (min-colors 89)) (:foreground "#d70000"))))
 '(dired-header ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(dired-ignored ((((class color) (min-colors 89)) (:inherit shadow))))
 '(dired-mark ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(dired-marked ((((class color) (min-colors 89)) (:foreground "#af00df" :inherit bold))))
 '(dired-perm-write ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :underline t))))
 '(dired-symlink ((((class color) (min-colors 89)) (:foreground "#00ffff" :background "#262626" :inherit bold))))
 '(dired-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(eldoc-highlight-function-argument ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(evil-ex-substitute-matches ((((class color) (min-colors 89)) (:background "#262626" :foreground "#d70000"))))
 '(evil-ex-substitute-replacement ((((class color) (min-colors 89)) (:background "#262626" :foreground "#67b11d"))))
 '(flycheck-error ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#e0211d"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#e0211d" :inherit bold :underline t))))
 '(flycheck-error-list-checker-name ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(flycheck-fringe-error ((((class color) (min-colors 89)) (:foreground "#e0211d" :inherit bold))))
 '(flycheck-fringe-info ((((class color) (min-colors 89)) (:foreground "#268bd2" :inherit bold))))
 '(flycheck-fringe-warning ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(flycheck-info ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#268bd2"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#268bd2" :inherit bold :underline t))))
 '(flycheck-warning ((((supports :underline (:style line)) (class color) (min-colors 89)) (:underline (:style line :color "#dc752f"))) (((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#dc752f" :inherit bold :underline t))))
 '(helm-bookmark-directory ((((class color) (min-colors 89)) (:inherit helm-ff-directory))))
 '(helm-bookmark-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(helm-bookmark-gnus ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(helm-bookmark-info ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(helm-bookmark-man ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(helm-bookmark-w3m ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(helm-buffer-directory ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-buffer-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-buffer-not-saved ((((class color) (min-colors 89)) (:foreground "#d75fd7" :background "#262626"))))
 '(helm-buffer-process ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#262626"))))
 '(helm-buffer-saved-out ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-buffer-size ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-candidate-number ((((class color) (min-colors 89)) (:background "#262626" :foreground "#268bd2" :inherit bold))))
 '(helm-ff-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#262626" :inherit bold))))
 '(helm-ff-dotted-directory ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#262626" :inherit bold))))
 '(helm-ff-dotted-symlink-directory ((((class color) (min-colors 89)) (:foreground "#00ffff" :background "#262626" :inherit bold))))
 '(helm-ff-executable ((((class color) (min-colors 89)) (:foreground "#86dc2f" :background "#262626" :weight normal))))
 '(helm-ff-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626" :weight normal))))
 '(helm-ff-invalid-symlink ((((class color) (min-colors 89)) (:foreground "#d70000" :background "#262626" :inherit bold))))
 '(helm-ff-prefix ((((class color) (min-colors 89)) (:foreground "#262626" :background "#268bd2" :weight normal))))
 '(helm-ff-symlink ((((class color) (min-colors 89)) (:foreground "#00ffff" :background "#262626" :inherit bold))))
 '(helm-grep-cmd-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-grep-file ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-grep-finish ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(helm-grep-lineno ((((class color) (min-colors 89)) (:foreground "#df005f" :background "#262626" :inherit bold))))
 '(helm-grep-match ((((class color) (min-colors 89)) (:foreground nil :background nil :inherit helm-match))))
 '(helm-header ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626" :underline nil :box nil))))
 '(helm-header-line-left-margin ((((class color) (min-colors 89)) (:foreground "#268bd2" :background nil))))
 '(helm-match ((((class color) (min-colors 89)) (:background "#262626" :foreground "#268bd2"))))
 '(helm-match-item ((((class color) (min-colors 89)) (:background "#262626" :foreground "#268bd2"))))
 '(helm-moccur-buffer ((((class color) (min-colors 89)) (:foreground "#8787d7" :background "#262626"))))
 '(helm-selection ((((class color) (min-colors 89)) (:background "#444444"))))
 '(helm-selection-line ((((class color) (min-colors 89)) (:background "#1c1c1c"))))
 '(helm-separator ((((class color) (min-colors 89)) (:foreground "#d75fd7" :background "#262626"))))
 '(helm-source-header ((((class color) (min-colors 89)) (:background "#d75fd7" :foreground "#262626" :inherit bold))))
 '(helm-visible-mark ((((class color) (min-colors 89)) (:foreground "#268bd2" :background "#121212"))))
 '(hydra-face-blue ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(hydra-face-red ((((class color) (min-colors 89)) (:foreground "#d70000"))))
 '(ido-first-match ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(ido-only-match ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold))))
 '(ido-subdir ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(ido-vertical-match-face ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline nil))))
 '(info-header-xref ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline t))))
 '(info-menu ((((class color) (min-colors 89)) (:foreground "#86dc2f"))))
 '(info-node ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(info-quoted-name ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(info-reference-item ((((class color) (min-colors 89)) (:background nil :underline t :inherit bold))))
 '(info-string ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(info-title-1 ((((class color) (min-colors 89)) (:height 1.4 :inherit bold))))
 '(info-title-2 ((((class color) (min-colors 89)) (:height 1.3 :inherit bold))))
 '(info-title-3 ((((class color) (min-colors 89)) (:height 1.3))))
 '(info-title-4 ((((class color) (min-colors 89)) (:height 1.2))))
 '(linum ((((class color) (min-colors 89)) (:foreground "#444444" :background "#1c1c1c"))))
 '(magit-blame-date ((((class color) (min-colors 89)) :background "#262626" :foreground "#67b11d")))
 '(magit-blame-hash ((((class color) (min-colors 89)) :background "#262626" :foreground "#d75fd7")))
 '(magit-blame-heading ((((class color) (min-colors 89)) :background "#262626" :foreground "#67b11d")))
 '(magit-blame-name ((((class color) (min-colors 89)) :background "#262626" :foreground "#875f00")))
 '(magit-blame-summary ((((class color) (min-colors 89)) :background "#262626" :foreground "#875f00")))
 '(magit-branch-current ((((class color) (min-colors 89)) (:background "#262626" :foreground "#268bd2" :inherit bold :box t))))
 '(magit-branch-local ((((class color) (min-colors 89)) (:background "#262626" :foreground "#268bd2" :inherit bold))))
 '(magit-branch-remote ((((class color) (min-colors 89)) (:background "#262626" :foreground "#2aa198" :inherit bold))))
 '(magit-diff-context-highlight ((((class color) (min-colors 89)) (:background "#1c1c1c" :foreground "#b2b2b2"))))
 '(magit-diff-file-heading ((((class color) (min-colors 89)) (:background "#262626" :foreground "#008787"))))
 '(magit-diff-file-heading-highlight ((((class color) (min-colors 89)) (:background "#262626" :foreground "#008787"))))
 '(magit-diff-hunk-heading ((((class color) (min-colors 89)) (:background "#444444" :foreground "#888888"))))
 '(magit-diff-hunk-heading-highlight ((((class color) (min-colors 89)) (:background "#444444" :foreground "#888888"))))
 '(magit-hash ((((class color) (min-colors 89)) (:foreground "#8787d7"))))
 '(magit-log-author ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(magit-process-ng ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(magit-process-ok ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(magit-reflog-amend ((((class color) (min-colors 89)) (:foreground "#af00df"))))
 '(magit-reflog-checkout ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(magit-reflog-cherry-pick ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-commit ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-merge ((((class color) (min-colors 89)) (:foreground "#67b11d"))))
 '(magit-reflog-other ((((class color) (min-colors 89)) (:foreground "#00ffff"))))
 '(magit-reflog-rebase ((((class color) (min-colors 89)) (:foreground "#af00df"))))
 '(magit-reflog-remote ((((class color) (min-colors 89)) (:foreground "#00ffff"))))
 '(magit-reflog-reset ((((class color) (min-colors 89)) (:foreground "#d70000"))))
 '(magit-section-heading ((((class color) (min-colors 89)) (:foreground "#268bd2" :inherit bold))))
 '(magit-section-highlight ((((class color) (min-colors 89)) (:background "#1c1c1c"))))
 '(mode-line ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#121212" :box (:color "#111111" :line-width 1)))))
 '(mode-line-buffer-id ((((class color) (min-colors 89)) (:inherit bold :foreground "#d75fd7"))))
 '(mode-line-inactive ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626" :box (:color "#111111" :line-width 1)))))
 '(org-agenda-clocking ((((class color) (min-colors 89)) (:background "#444444" :foreground "#d75fd7"))))
 '(org-agenda-date ((((class color) (min-colors 89)) (:foreground "#8787d7" :height 1.1))))
 '(org-agenda-date-today ((((class color) (min-colors 89)) (:foreground "#268bd2" :inherit bold :height 1.3))))
 '(org-agenda-date-weekend ((((class color) (min-colors 89)) (:inherit bold :foreground "#8787d7"))))
 '(org-agenda-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :height 1.2))))
 '(org-agenda-structure ((((class color) (min-colors 89)) (:inherit bold :foreground "#d75fd7"))))
 '(org-block ((((class color) (min-colors 89)) (:background "#262626" :foreground "#b2b2b2"))))
 '(org-block-begin-line ((((class color) (min-colors 89)) (:background "#333333" :foreground "#af5faf"))))
 '(org-block-end-line ((((class color) (min-colors 89)) (:background "#333333" :foreground "#af5faf"))))
 '(org-clock-overlay ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(org-code ((((class color) (min-colors 89)) (:foreground "#00ffff"))))
 '(org-column ((((class color) (min-colors 89)) (:background "#444444"))))
 '(org-column-title ((((class color) (min-colors 89)) (:background "#444444"))))
 '(org-date ((((class color) (min-colors 89)) (:underline t :foreground "#8787d7"))))
 '(org-date-selected ((((class color) (min-colors 89)) (:background "#d75fd7" :foreground "#262626"))))
 '(org-document-info-keyword ((((class color) (min-colors 89)) (:foreground "#af875f"))))
 '(org-document-title ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold :height 1.4 :underline t))))
 '(org-done ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :background "#262626"))))
 '(org-ellipsis ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-footnote ((((class color) (min-colors 89)) (:underline t :foreground "#b2b2b2"))))
 '(org-hide ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-kbd ((((class color) (min-colors 89)) (:inherit region :foreground "#b2b2b2" :box (:line-width 1 :style released-button)))))
 '(org-level-1 ((((class color) (min-colors 89)) (:inherit bold :foreground "#268bd2" :height 1.3 :background nil))))
 '(org-level-2 ((((class color) (min-colors 89)) (:inherit bold :foreground "#2aa198" :height 1.2 :background nil))))
 '(org-level-3 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d" :height 1.1 :background nil))))
 '(org-level-4 ((((class color) (min-colors 89)) (:bold nil :foreground "#875f00" :background nil))))
 '(org-level-5 ((((class color) (min-colors 89)) (:bold nil :foreground "#268bd2"))))
 '(org-level-6 ((((class color) (min-colors 89)) (:bold nil :foreground "#2aa198"))))
 '(org-level-7 ((((class color) (min-colors 89)) (:bold nil :foreground "#67b11d"))))
 '(org-level-8 ((((class color) (min-colors 89)) (:bold nil :foreground "#875f00"))))
 '(org-link ((((class color) (min-colors 89)) (:underline t :foreground "#008787"))))
 '(org-meta-line ((((class color) (min-colors 89)) (:foreground "#af875f"))))
 '(org-mode-line-clock-overrun ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(org-priority ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold))))
 '(org-quote ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-scheduled ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(org-scheduled-today ((((class color) (min-colors 89)) (:foreground "#d75fd7" :height 1.2))))
 '(org-sexp-date ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(org-special-keyword ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(org-table ((((class color) (min-colors 89)) (:foreground "#b2b2b2" :background "#262626"))))
 '(org-time-grid ((((class color) (min-colors 89)) (:foreground "#2aa198"))))
 '(org-todo ((((class color) (min-colors 89)) (:foreground "#dc752f" :inherit bold :background "#262626"))))
 '(org-verbatim ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(org-verse ((((class color) (min-colors 89)) (:inherit org-block :slant italic))))
 '(org-warning ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(powerline-active1 ((((class color) (min-colors 89)) (:background "#444444" :foreground "#b2b2b2"))))
 '(powerline-active2 ((((class color) (min-colors 89)) (:background "#444444" :foreground "#b2b2b2"))))
 '(powerline-inactive1 ((((class color) (min-colors 89)) (:background "#1c1c1c" :foreground "#b2b2b2"))))
 '(powerline-inactive2 ((((class color) (min-colors 89)) (:background "#1c1c1c" :foreground "#b2b2b2"))))
 '(rainbow-delimiters-depth-1-face ((((class color) (min-colors 89)) :foreground "#268bd2")))
 '(rainbow-delimiters-depth-2-face ((((class color) (min-colors 89)) :foreground "#d75fd7")))
 '(rainbow-delimiters-depth-3-face ((((class color) (min-colors 89)) :foreground "#2aa198")))
 '(rainbow-delimiters-depth-4-face ((((class color) (min-colors 89)) :foreground "#67b11d")))
 '(rainbow-delimiters-depth-5-face ((((class color) (min-colors 89)) :foreground "#875f00")))
 '(rainbow-delimiters-depth-6-face ((((class color) (min-colors 89)) :foreground "#268bd2")))
 '(rainbow-delimiters-depth-7-face ((((class color) (min-colors 89)) :foreground "#d75fd7")))
 '(rainbow-delimiters-depth-8-face ((((class color) (min-colors 89)) :foreground "#2aa198")))
 '(rainbow-delimiters-mismatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(rainbow-delimiters-unmatched-face ((((class color) (min-colors 89)) :foreground "#e0211d" :overline t)))
 '(show-paren-match ((((class color) (min-colors 89)) (:background "#262626"))))
 '(show-paren-mismatch ((((class color) (min-colors 89)) (:background "#262626"))))
 '(sp-pair-overlay-face ((((class color) (min-colors 89)) (:background "#444444" :foreground nil))))
 '(sp-show-pair-match-face ((((class color) (min-colors 89)) (:foreground "#86dc2f" :inherit bold :underline t))))
 '(spaceline-flycheck-error ((((class color) (min-colors 89)) (:foreground "#e0211d"))))
 '(spaceline-flycheck-info ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(spaceline-flycheck-warning ((((class color) (min-colors 89)) (:foreground "#dc752f"))))
 '(spaceline-python-venv ((((class color) (min-colors 89)) (:foreground "#d75fd7"))))
 '(spacemacs-transient-state-title-face ((((class color) (min-colors 89)) (:background nil :foreground "#d75fd7" :box nil :inherit bold))))
 '(which-key-command-description-face ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(which-key-group-description-face ((((class color) (min-colors 89)) (:foreground "#268bd2"))))
 '(which-key-key-face ((((class color) (min-colors 89)) (:foreground "#d75fd7" :inherit bold))))
 '(which-key-separator-face ((((class color) (min-colors 89)) (:background nil :foreground "#2aa198"))))
 '(which-key-special-key-face ((((class color) (min-colors 89)) (:background "#d75fd7" :foreground "#262626"))))
 '(ffap ((((class color) (min-colors 89)) (:foreground "#b2b2b2"))))
 '(flx-highlight-face ((((class color) (min-colors 89)) (:foreground "#d75fd7" :underline nil))))
 '(trailing-whitespace ((((class color) (min-colors 89)) :foreground nil :background "#e0211d")))
 '(undo-tree-visualizer-current-face ((((class color) (min-colors 89)) :foreground "#268bd2")))
 '(undo-tree-visualizer-default-face ((((class color) (min-colors 89)) :foreground "#b2b2b2")))
 '(undo-tree-visualizer-register-face ((((class color) (min-colors 89)) :foreground "#d75fd7")))
 '(undo-tree-visualizer-unmodified-face ((((class color) (min-colors 89)) :foreground "#8787d7")))
 '(default ((t (:foreground "#b2b2b2")))))

(provide-theme 'spacemacs-dark-disable-background)
